-- CRIAÇÃO DO BANCO
CREATE DATABASE SCA_242;
USE SCA_242;

-- CRIAÇÃO DAS TABELAS
CREATE TABLE TB_CURSO (
    Id_Curso INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Duracao INT NOT NULL
);

CREATE TABLE TB_ALUNO (
    Matricula INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Idade INT NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Id_Curso INT,
    FOREIGN KEY (Id_Curso) REFERENCES TB_CURSO(Id_Curso)
);

CREATE TABLE TB_PROFESSOR (
    SIAP INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);

CREATE TABLE TB_DISCIPLINA (
    Id_Disciplina INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Duracao INT NOT NULL,
    Id_Curso INT NOT NULL,
    FOREIGN KEY (Id_Curso) REFERENCES TB_CURSO(Id_Curso)
);

CREATE TABLE TB_MATRICULADOS (
    Matricula INT NOT NULL,
    Id_Disciplina INT NOT NULL,
    PRIMARY KEY (Matricula, Id_Disciplina),
    FOREIGN KEY (Matricula) REFERENCES TB_ALUNO(Matricula),
    FOREIGN KEY (Id_Disciplina) REFERENCES TB_DISCIPLINA(Id_Disciplina)
);

CREATE TABLE TB_AULAS (
    SIAP INT NOT NULL,
    Id_Curso INT NOT NULL,
    PRIMARY KEY (SIAP, Id_Curso),
    FOREIGN KEY (SIAP) REFERENCES TB_PROFESSOR(SIAP),
    FOREIGN KEY (Id_Curso) REFERENCES TB_CURSO(Id_Curso)
);

CREATE TABLE TB_ENSINAR (
    SIAP INT NOT NULL,
    Id_Disciplina INT NOT NULL,
    PRIMARY KEY (SIAP, Id_Disciplina),
    FOREIGN KEY (SIAP) REFERENCES TB_PROFESSOR(SIAP),
    FOREIGN KEY (Id_Disciplina) REFERENCES TB_DISCIPLINA(Id_Disciplina)
);

-- INSERT
INSERT INTO TB_CURSO (Nome, Id_Curso, Duracao)
VALUES ('Informatica', 60, 2000),
       ('Quimica', 30, 2000);

INSERT INTO TB_ALUNO (Nome, Matricula, Idade, Email, Id_Curso)
VALUES ('Lorran', 20232011060333, 17, 'lorran@gmail.com', 60),
       ('Alyne', 20232011060444, 16, 'alyne@gmail.com', 30);

INSERT INTO TB_PROFESSOR (Nome, SIAP, Email)
VALUES ('Taveira', 12345, 'taveira@gmail.com'),
       ('Renata', 54321, 'renata@gmail.com'),
       ('Cesar', 123456, 'cesar@gmail.com');

INSERT INTO TB_DISCIPLINA (Nome, Id_Disciplina, Id_Curso, Duracao)
VALUES ('Banco de Dados', 1, 60, 20),
       ('FUNPROII', 2, 60, 20);

INSERT INTO TB_MATRICULADOS (Matricula, Id_Disciplina)
VALUES (20232011060333, 1),
       (20232011060444, 2);

INSERT INTO TB_AULAS (SIAP, Id_Curso)
VALUES (12345, 60),
       (54321, 30);

INSERT INTO TB_ENSINAR (SIAP, Id_Disciplina)
VALUES (12345, 1),
       (123456, 2);

-- SELECT
SELECT * FROM TB_CURSO;
SELECT * FROM TB_ALUNO;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_DISCIPLINA;
SELECT * FROM TB_MATRICULADOS;
SELECT * FROM TB_AULAS;
SELECT * FROM TB_ENSINAR;

-- UPDATE
UPDATE TB_ALUNO
SET Nome = 'Arlenson Lorran'
WHERE Matricula = 20232011060333;

UPDATE TB_CURSO
SET Duracao = 2100
WHERE Id_Curso = 60;

UPDATE TB_PROFESSOR
SET Nome = 'Renata Silveira'
WHERE SIAP = 54321;

UPDATE TB_DISCIPLINA
SET Nome = 'Banco de Dados Avançado'
WHERE Id_Disciplina = 1;

-- Trocar disciplina matriculada
DELETE FROM TB_MATRICULADOS
WHERE Matricula = 20232011060333 AND Id_Disciplina = 1;

INSERT INTO TB_MATRICULADOS (Matricula, Id_Disciplina)
VALUES (20232011060333, 2);

-- Trocar aula de curso
DELETE FROM TB_AULAS
WHERE SIAP = 12345 AND Id_Curso = 60;

INSERT INTO TB_AULAS (SIAP, Id_Curso)
VALUES (12345, 30);

-- Trocar disciplina ensinada
DELETE FROM TB_ENSINAR
WHERE SIAP = 123456 AND Id_Disciplina = 2;

INSERT INTO TB_ENSINAR (SIAP, Id_Disciplina)
VALUES (123456, 1);

-- DELETE
DELETE FROM TB_MATRICULADOS
WHERE Matricula = 20232011060444;

DELETE FROM TB_ALUNO
WHERE Matricula = 20232011060444;

DELETE FROM TB_AULAS
WHERE SIAP = 54321;

DELETE FROM TB_PROFESSOR
WHERE SIAP = 54321;

DELETE FROM TB_ENSINAR
WHERE SIAP = 123456 AND Id_Disciplina = 1;

DELETE FROM TB_MATRICULADOS
WHERE Matricula = 20232011060333 AND Id_Disciplina = 2;

DELETE FROM TB_DISCIPLINA
WHERE Id_Disciplina = 2;

DELETE FROM TB_AULAS
WHERE SIAP = 12345 AND Id_Curso = 30;

DELETE FROM TB_CURSO
WHERE Id_Curso = 30;
